export const ACTION_CONSTANTS = {
  ADD_NEW_SERVICE: "SERVICE_REQUESTS/ADD_SERVICE",
  UPDATE_SR_STATUS: "SERVICE_REQUESTS/UPDATE_SR_STATUS",
  CANCEL_SR: "SERVICE_REQUESTS/CANCEL_SR",
  UPDATE_SR: "SERVICE_REQUESTS/UPDATE_SR",
  FETCH_SERVICE_REQUESTS: "SERVICE_REQUESTS/FETCH_SERVICES",

  // AUCTIONS
  FETCH_AUCTIONS: "SERVICE_REQUESTS/FETCH_AUCTIONS",
  PLACE_BID: "SERVICE_REQUESTS/PLACE_BID",
  CHECK_AUCTION_WINNER: "SERVICE_REQUESTS/CHECK_AUCTION_WINNER",

  // DISPUTES
  FETCH_DISPUTES: "SERVICE_REQUESTS/FETCH_DISPUTES",
  VOTE_DISPUTE: "SERVICE_REQUESTS/VOTE_DISPUTE",
  CHECK_DISPUTE_WINNER: "SERVICE_REQUESTS/CHECK_DISPUTE_WINNER",
};
