export const ACTION_CONSTANTS = {
  FETCH_ROLES: "USERS/FETCH_ROLES",
  FETCH_ALL_ROLE_REQUESTS: "USERS/FETCH_ALL_ROLE_REQUESTS",
  FETCH_USER_ROLES: "USERS/FETCH_USER_ROLES",
  ADD_NEW_ROLE: "USERS/ADD_NEW_ROLE",
  SAVE_USER_INFO: "USERS/SAVE_USER_INFO",
  GET_USER_INFO: "USERS/GET_USER_INFO",
  UPDATE_USER_INFO_ON_CHANGE: "USERS/UPDATE_USER_INFO_ON_CHANGE",
  CANCEL_ROLE_REQUEST: "USERS/CANCEL_ROLE_REQUEST",
  ACT_ON_ROLE_REQUEST: "USERS/ACT_ON_ROLE_REQUEST",
  FETCH_DL: "USERS/FETCH_DL",
  SUBMIT_DL: "USERS/SUBMIT_DL",
};
